/**
 * Tutorial definitions ported to @postpilot/tutorial-sdk types.
 * These will be refined as the custom tutorial system matures.
 */

import type { TutorialDefinition } from "@postpilot/tutorial-sdk";

// ── Overview Tours ──────────────────────────────────────────────────────────

const OVERVIEW_APP: TutorialDefinition = {
  id: "overview-app",
  name: "Full Application Overview",
  description: "Tour the main navigation and workspace layout",
  mode: "informational",
  category: "overview",
  chainToTutorialId: "howto-idea-generation",
  finishButtonText: "Create your first post →",
  chainDeclineText: "No thanks, I'll explore on my own",
  steps: [
    {
      id: "app-nav",
      icon: "🧭",
      title: "Your Navigation",
      content: "This sidebar is your main menu. It takes you to every part of PostPilot: your Dashboard, Idea Bank, Posts, Library, Calendar, and Analytics.",
      selector: "#tour-sidebar-nav",
      position: { anchor: "element", side: "right" },
      route: "/dashboard",
    },
    {
      id: "app-settings",
      icon: "⚙️",
      title: "Settings, Help & Profile",
      content: "Down here you'll find your Settings (AI provider, LinkedIn connection), Help Center (guides and tutorials), and your Profile (expertise, voice, and subscription).",
      selector: "#tour-sidebar-settings",
      position: { anchor: "element", side: "right" },
    },
    {
      id: "app-top-controls",
      icon: "🎨",
      title: "Theme & Sign Out",
      content: "Use the sun/moon icon to switch between light and dark mode. The arrow icon next to it signs you out of PostPilot.",
      selector: "#tour-top-controls",
      position: { anchor: "element", side: "bottom" },
    },
    {
      id: "app-workspace",
      icon: "🎉",
      title: "Ready to Create Your First Post?",
      content: "Now that you know your way around, would you like to be guided through creating your first LinkedIn post? We'll walk you through generating ideas, developing one into a draft, and editing it in the post editor.",
      selector: "#tour-quick-actions",
      position: { anchor: "element", side: "bottom" },
    },
  ],
  relatedTutorials: ["howto-idea-generation", "howto-develop-idea"],
};

const OVERVIEW_DASHBOARD: TutorialDefinition = {
  id: "overview-dashboard",
  name: "Dashboard Overview",
  description: "Metrics, quick actions, drafts, usage, and content balance",
  mode: "informational",
  category: "overview",
  showTutorialListOnFinish: true,
  steps: [
    {
      id: "dash-metrics",
      icon: "📊",
      title: "Your Content Stats",
      content: "These cards show your content numbers at a glance: total posts, scheduled posts, and published posts. They update automatically as you work.",
      selector: "#tour-dashboard-metrics",
      position: { anchor: "element", side: "bottom" },
      route: "/dashboard",
    },
    {
      id: "dash-actions",
      icon: "🚀",
      title: "Quick Actions",
      content: "Your starting points. Generate Ideas opens the AI brainstorming tool. Start New Post creates a blank post. View Calendar shows your publishing schedule.",
      selector: "#tour-quick-actions",
      position: { anchor: "element", side: "bottom" },
    },
    {
      id: "dash-drafts",
      icon: "📝",
      title: "Recent Drafts",
      content: "Your latest draft posts appear here for quick access. Click any draft to jump straight into editing it.",
      selector: "#tour-recent-drafts",
      position: { anchor: "element", side: "top" },
    },
    {
      id: "dash-ideas",
      icon: "💡",
      title: "Recent Ideas",
      content: "Your latest content ideas are shown here. Click any idea to go directly to it in your Idea Bank where you can develop it further or turn it into a post.",
      selector: "#tour-recent-ideas",
      position: { anchor: "element", side: "top" },
    },
    {
      id: "dash-usage",
      icon: "📈",
      title: "Monthly Usage",
      content: "Track how much of your monthly plan you've used: posts created, brainstorms, AI messages, and scheduled posts. This resets each month.",
      selector: "#tour-usage-summary",
      position: { anchor: "element", side: "left" },
    },
    {
      id: "dash-balance",
      icon: "⚖️",
      title: "Content Balance",
      content: "This section shows the distribution of your posts across your content pillars. It helps you see which topics you're covering most and where you might want to diversify. The data is based on the content pillars you assign when creating posts or ideas.",
      selector: "#tour-content-balance",
      position: { anchor: "element", side: "left" },
    },
    {
      id: "dash-done",
      icon: "🎉",
      title: "That's Your Dashboard!",
      content: "Ready to create some content? Try the Idea Generation tutorial to get started, or explore on your own.",
      selector: "#tour-quick-actions",
      position: { anchor: "element", side: "bottom" },
    },
  ],
  relatedTutorials: ["howto-idea-generation"],
};

const OVERVIEW_IDEAS: TutorialDefinition = {
  id: "overview-ideas",
  name: "Idea Bank Overview",
  description: "Process flow, idea generator, filters, and idea cards",
  mode: "informational",
  showTutorialListOnFinish: true,
  category: "overview",
  steps: [
    {
      id: "ideas-flow",
      icon: "🔄",
      title: "The Idea Workflow",
      content: "PostPilot follows a simple 3-step process: Generate ideas with AI, filter and organize your favorites, then develop the best ones into LinkedIn posts.",
      selector: "#tour-idea-process-flow",
      position: { anchor: "element", side: "bottom" },
      route: "/ideas",
    },
    {
      id: "ideas-gen",
      icon: "✨",
      title: "AI Idea Generator",
      content: "Click this to start a new brainstorming session. The AI uses your expertise, content pillars, and audience to suggest relevant content ideas.",
      selector: "#tour-generate-ideas-btn",
      position: { anchor: "element", side: "bottom" },
    },
    {
      id: "ideas-filter",
      icon: "🔍",
      title: "Filter & Search",
      content: "Use the status filters to switch between Open ideas (Captured, Developing) and Closed ideas (Converted, Archived), or search by keyword.",
      selector: "#tour-idea-filters",
      position: { anchor: "element", side: "bottom" },
    },
    {
      id: "ideas-cards",
      icon: "💡",
      title: "Your Idea Cards",
      content: "Each idea card shows the title, description, status, and content pillar. Use the buttons to Edit, Archive, or Develop an idea into a full post.",
      selector: "#tour-idea-card",
      position: { anchor: "element", side: "top" },
    },
    {
      id: "ideas-done",
      icon: "🎉",
      title: "That's the Idea Bank!",
      content: "Want to try generating your first ideas? Check out the step-by-step Idea Generation tutorial.",
      position: { anchor: "viewport" },
    },
  ],
  relatedTutorials: ["howto-idea-generation"],
};

const OVERVIEW_POSTS: TutorialDefinition = {
  id: "overview-posts",
  name: "Posts Page Overview",
  description: "Metrics, filters, card actions, and new post options",
  mode: "informational",
  category: "overview",
  showTutorialListOnFinish: true,
  steps: [
    {
      id: "posts-metrics",
      icon: "📊",
      title: "Post Metrics",
      content: "These cards give you a quick count of your total posts, how many are scheduled, and how many have been published to LinkedIn.",
      selector: "#tour-posts-metrics",
      position: { anchor: "element", side: "bottom" },
      route: "/posts",
    },
    {
      id: "posts-new",
      icon: "➕",
      title: "Start a New Post",
      content: "Click the 'New Post' button to create a blank post and open it in the editor. You can also start posts from the Dashboard or by developing an idea from the Idea Bank.",
      selector: "#tour-posts-new-post",
      position: { anchor: "element", side: "bottom" },
    },
    {
      id: "posts-filters",
      icon: "🔍",
      title: "Filter by Status",
      content: "Use these tabs to filter your posts. 'In Work' shows drafts and scheduled posts. 'Complete' shows published and archived posts. You can also drill into specific statuses like Drafts, Scheduled, or Posted.",
      selector: "#tour-posts-filters",
      position: { anchor: "element", side: "bottom" },
    },
    {
      id: "posts-cards",
      icon: "📄",
      title: "Post Cards and Actions",
      content: "Each card shows a post's title, content preview, and status. Click any card to open it in the editor. Use the Actions button at the bottom to Post to LinkedIn, Schedule, mark as Manually Posted, Archive, or Delete.",
      selector: "#tour-posts-cards",
      position: { anchor: "element", side: "top" },
    },
  ],
  relatedTutorials: ["howto-post-creation"],
};

const OVERVIEW_CALENDAR: TutorialDefinition = {
  id: "overview-calendar",
  name: "Calendar Page Overview",
  description: "Calendar views, scheduled posts, and quick actions",
  mode: "informational",
  category: "overview",
  showTutorialListOnFinish: true,
  steps: [
    {
      id: "cal-intro",
      icon: "📅",
      title: "Your Content Calendar",
      content: "This is your publishing schedule at a glance. All your scheduled posts appear here organized by date so you can plan your content strategy visually.",
      position: { anchor: "viewport" },
      route: "/calendar",
    },
    {
      id: "cal-grid",
      icon: "🗓️",
      title: "The Calendar Grid",
      content: "Each post appears as a colored pill on its scheduled date. The colors match the post status: purple for Scheduled, green for Posted to LinkedIn, and yellow for Drafts. Click any date to drill into that day's posts.",
      selector: "#tour-calendar-grid",
      position: { anchor: "element", side: "bottom" },
    },
    {
      id: "cal-views",
      icon: "👁️",
      title: "Calendar Views",
      content: "Switch between three views. Month shows the big picture of your schedule. Week gives more detail with post images and descriptions. Day shows hourly timeslots for precise scheduling.",
      selector: "#tour-calendar-views",
      position: { anchor: "element", side: "bottom" },
    },
    {
      id: "cal-upcoming",
      icon: "⏰",
      title: "Upcoming Posts",
      content: "Your next scheduled posts are listed here, sorted by date. Each card shows the post title, scheduled publish time, and status.",
      selector: "#tour-upcoming-posts",
      position: { anchor: "element", side: "left" },
    },
    {
      id: "cal-view-toggle",
      icon: "🔀",
      title: "Card and List Views",
      content: "Use these buttons to switch between Card view and List view. Card view shows post images and details. List view gives you a compact summary when you have many scheduled posts.",
      selector: "#tour-upcoming-view-toggle",
      position: { anchor: "element", side: "bottom" },
    },
    {
      id: "cal-done",
      icon: "🎉",
      title: "That's the Calendar!",
      content: "Need to manage your schedule? Check out the Scheduled Post Management tutorial.",
      position: { anchor: "viewport" },
    },
  ],
  relatedTutorials: ["howto-scheduled-posts"],
};

const OVERVIEW_SYSTEM: TutorialDefinition = {
  id: "overview-system",
  name: "System Management Overview",
  description: "Settings, Help Center, and Profile",
  mode: "informational",
  category: "overview",
  showTutorialListOnFinish: true,
  steps: [
    {
      id: "sys-settings",
      icon: "⚙️",
      title: "Settings",
      content: "Settings is where you connect your LinkedIn account, manage workspace settings, and choose your app theme. If your subscription plan includes Bring Your Own Key (BYOK), you can also configure your AI provider and API key here.",
      position: { anchor: "viewport", x: 40, y: 200 },
      route: "/settings",
    },
    {
      id: "sys-help",
      icon: "❓",
      title: "Help Center",
      content: "The Help Center has detailed guides for every feature, step-by-step tutorials, and the ability to restart any guided tour.",
      position: { anchor: "viewport", x: 40, y: 200 },
      route: "/help",
    },
    {
      id: "sys-profile",
      icon: "👤",
      title: "Your Profile",
      content: "Your Profile stores your expertise, writing voice, content pillars, and subscription plan. The AI uses this information to generate content that sounds like you.",
      position: { anchor: "viewport", x: 40, y: 200 },
      route: "/profile",
    },
  ],
};

// ── How-To Tutorials ────────────────────────────────────────────────────────

const HOWTO_IDEA_GENERATION: TutorialDefinition = {
  id: "howto-idea-generation",
  name: "How to Generate Ideas with AI",
  description: "Use the AI Idea Generator to brainstorm content ideas",
  mode: "interactive",
  category: "howto",
  showTutorialListOnFinish: true,
  chainToTutorialId: "howto-develop-idea",
  finishButtonText: "Develop an idea into a post →",
  steps: [
    {
      id: "gen-start",
      icon: "💡",
      title: "Let's Generate Some Ideas",
      content: "Click the 'Generate Ideas' button to open the AI Idea Generator. It will take you to the Idea Bank where you can brainstorm content topics.",
      selector: "#tour-generate-ideas",
      position: { anchor: "element", side: "bottom" },
      route: "/dashboard",
      action: "click",
      clickTarget: "#tour-generate-ideas",
    },
    {
      id: "gen-topic",
      icon: "🎯",
      title: "Enter a Topic",
      content: "Type a topic you'd like to create content about. This can be anything related to your expertise, such as a trend, a lesson learned, a hot take, or a question your audience asks.",
      position: { anchor: "viewport", x: 40, y: 200 },
      action: "formInput",
      clickTarget: "#gen-topic",
    },
    {
      id: "gen-pillar",
      icon: "📂",
      title: "Select a Content Pillar",
      content: "Choose one or more content pillars that match your topic. Pillars help categorize your content and ensure you post about a variety of subjects. When you are ready, click the Generate Ideas button.",
      position: { anchor: "viewport", x: 40, y: 200 },
      action: "click",
      clickTarget: "#tour-generate-btn",
    },
    {
      id: "gen-waiting",
      icon: "✨",
      title: "Generating Your Ideas",
      content: "The AI is brainstorming content ideas based on your topic, expertise, and audience. This usually takes just a few seconds.",
      position: { anchor: "viewport", x: 40, y: 200 },
      action: "elementExists",
      waitForElement: "#tour-generated-ideas",
    },
    {
      id: "gen-select",
      icon: "✅",
      title: "Save Ideas to Your Idea Bank",
      content: "Browse the generated ideas and click 'Save to Idea Bank' on any that look like good candidates for posts. You can save as many ideas as you want. Only the ones you later choose to develop will move forward in the process. Click Next when you are done saving ideas.",
      position: { anchor: "viewport", x: 40, y: 200 },
      action: "manual",
    },
    {
      id: "gen-done",
      icon: "🎉",
      title: "Ideas Saved to Your Idea Bank!",
      content: "Your saved ideas are now in your Idea Bank. From here you can develop any idea into a full LinkedIn post. Ready to try it?",
      selector: "#tour-idea-card",
      position: { anchor: "element", side: "top" },
      route: "/ideas",
    },
  ],
  relatedTutorials: ["howto-develop-idea"],
};

const HOWTO_DEVELOP_IDEA: TutorialDefinition = {
  id: "howto-develop-idea",
  name: "How to Develop an Idea into a Post",
  description: "Turn an idea into a polished LinkedIn post using the editor",
  mode: "interactive",
  category: "howto",
  showTutorialListOnFinish: true,
  steps: [
    {
      id: "dev-select",
      icon: "💡",
      title: "Choose an Idea to Develop",
      content: "Find an idea you'd like to turn into a LinkedIn post and click the 'Develop' button. The AI will automatically create an initial draft based on the idea.",
      selector: "#tour-idea-card",
      position: { anchor: "element", side: "top" },
      route: "/ideas",
      action: "navigate",
      waitForRoute: "/posts",
    },
    {
      id: "dev-progress",
      icon: "📊",
      title: "Your Post's Journey",
      content: "This progress bar tracks where your post is in the workflow: Draft, Scheduled, or Published. Timestamps appear as you move through each stage.",
      selector: "#tour-progress-bar",
      position: { anchor: "element", side: "bottom" },
      action: "manual",
    },
    {
      id: "dev-ai-draft",
      icon: "🤖",
      title: "AI Creates Your Initial Draft",
      content: "The AI Assistant automatically creates an initial draft based on your idea. You can see it working in the chat panel on the right. It uses your writing voice, expertise, and the idea description to produce a starting point.",
      selector: "#tour-ai-chat-area",
      position: { anchor: "element", side: "left" },
      action: "manual",
    },
    {
      id: "dev-apply",
      icon: "📋",
      title: "Apply Draft to Your Editor",
      content: "Click the 'Apply to Editor' button to move the AI-generated draft into your editor window. This is the fastest way to go from idea to editable content.",
      selector: "#tour-apply-to-editor",
      position: { anchor: "element", side: "left" },
      action: "manual",
    },
    {
      id: "dev-content",
      icon: "✍️",
      title: "Edit Your Content",
      content: "This is your writing space. Everything auto-saves as you type (look for the cloud icon). LinkedIn allows up to 3,000 characters. Edit the AI's draft to make it sound like you.",
      selector: "#tour-editor-content",
      position: { anchor: "element", side: "top" },
      action: "manual",
    },
    {
      id: "dev-emojis",
      icon: "😀",
      title: "Add Emojis & Formatting",
      content: "Use the emoji picker to add personality. The Format menu gives you line breaks, bullet points, Hook Analysis (AI feedback on your opening lines), and Copy Post.",
      selector: "#tour-formatting-toolbar",
      position: { anchor: "element", side: "bottom" },
      action: "manual",
    },
    {
      id: "dev-ai-chat",
      icon: "💬",
      title: "Chat with Your AI Assistant",
      content: "You can continue to use the AI Assistant at any time. Try quick suggestions like 'Add a hook', 'Make it shorter', or type your own request. It knows your voice and everything about your current post.",
      selector: "#tour-ai-panel",
      position: { anchor: "element", side: "left" },
      action: "manual",
    },
    {
      id: "dev-hashtags",
      icon: "#️⃣",
      title: "Add Hashtags",
      content: "Click 'Suggest' to let AI recommend relevant hashtags, or type your own. Hashtags help your post reach people beyond your network. LinkedIn recommends 3-5 per post.",
      selector: "#tour-hashtags",
      position: { anchor: "element", side: "top" },
      action: "manual",
    },
    {
      id: "dev-versions",
      icon: "💾",
      title: "Save & Manage Versions",
      content: "Save different versions of your post to explore multiple approaches to the same topic. You can compare versions side-by-side and pick your favorite.",
      selector: "#tour-versions-menu",
      position: { anchor: "element", side: "top" },
      action: "manual",
    },
    {
      id: "dev-publish",
      icon: "🚀",
      title: "Publish or Schedule",
      content: "When you're ready, use the Actions menu. 'Post to LinkedIn' opens a preview first so you can confirm before it goes live. 'Schedule Post' lets you pick a future date and time.",
      selector: "#tour-actions-menu",
      position: { anchor: "element", side: "top" },
      action: "manual",
    },
  ],
  relatedTutorials: ["howto-idea-generation"],
};

// ── Registry ────────────────────────────────────────────────────────────────

export const TUTORIAL_REGISTRY: Record<string, TutorialDefinition> = {
  "overview-app": OVERVIEW_APP,
  "overview-dashboard": OVERVIEW_DASHBOARD,
  "overview-ideas": OVERVIEW_IDEAS,
  "overview-posts": OVERVIEW_POSTS,
  "overview-calendar": OVERVIEW_CALENDAR,
  "overview-system": OVERVIEW_SYSTEM,
  "howto-idea-generation": HOWTO_IDEA_GENERATION,
  "howto-develop-idea": HOWTO_DEVELOP_IDEA,
};
